wynton-job: start working on fancy output of qstat -j

diff --git a/bin/wynton-job b/bin/wynton-job
--- a/bin/wynton-job
+++ b/bin/wynton-job
@@ -11,9 +11,29 @@
 ### Examples:
 ###  wynton job $JOBID
 ###
-### Version: 0.1.1
+### Version: 0.1.1-9000
 ### Copyright: Henrik Bengtsson (2020-2023)
 ### License: GPL (>= 2.1) [https://www.gnu.org/licenses/gpl.html]
+
+this="${BASH_SOURCE%/}"
+[[ -L "${this}" ]] && this=$(readlink "${this}")
+
+## Import bash utility functions
+incl="$(dirname "${this}")/incl"
+
+# shellcheck source=incl/asserts.sh
+source "${incl}/asserts.sh"
+# shellcheck source=incl/cli.sh
+source "${incl}/cli.sh"
+# shellcheck source=incl/conditions.sh
+source "${incl}/conditions.sh"
+# shellcheck source=incl/files.sh
+source "${incl}/files.sh"
+# shellcheck source=incl/output.sh
+source "${incl}/output.sh"
+# shellcheck source=incl/system.sh
+source "${incl}/system.sh"
+
 call="$0 $*"
 
 
@@ -37,24 +57,46 @@ function vecho() {
     fi
 }
 
-function version() {
-    grep -E "^###[ ]*Version:[ ]*" "$0" | sed 's/###[ ]*Version:[ ]*//g'
+function ok() {
+    echo "[ OK ]"
 }
 
-function help() {
-    local res=
-    res=$(grep "^###" "$0" | grep -vE '^(####|### whatis: )' | cut -b 5-)
-    if [[ ${UCSF_WYNTON_TOOLS} == true ]]; then
-        res=$(printf "%s\\n" "${res[@]}" | sed -E 's/([^/])wynton-([a-z]+)/\1wynton \2/')
+function fail() {
+    echo "[FAIL]"
+}
+
+function dir_info() {
+    local dir=${1:?}
+    local is_owner=${2:true}
+    local info
+    info="'${dir}'"
+
+    if [[ ! -d "${dir}" ]]; then
+        if ${is_owner}; then
+            info="${dir} ${red}ERROR: not a directory${reset}"
+        else
+            info="${dir} ${yellow}Cannot access directory because you ($USER) may lack access permissions${reset}"
+        fi
+        echo "${info}"
+        return 1
     fi
-    printf "%s\\n" "${res[@]}"
-}
 
+    ## File-permission, username, and group
+    info="${info} [$(stat -c "%A, owner=%U, group=%G" "${dir}")]"
+
+    echo "${info}"
+}
 
 # -------------------------------------------------------------------------
 # SPECIFIC
 # -------------------------------------------------------------------------
 
+## Enable terminal colors, if supported
+term_colors enable
+
+ok="${green}OK${reset}"
+warn="${yellow}WARN${reset}"
+fail="${red}FAIL${reset}"
 
 # -------------------------------------------------------------------------
 # MAIN
@@ -102,23 +144,180 @@ if [[ $action == "version" ]]; then
     version
     exit 0
 elif [[ $action == "help" ]]; then
-    help 
+    help "full"
     exit 0
 fi
 
 if [[ $action == "job" ]]; then
     [[ -z $jobid ]] && merror "Job ID not specified"
     
-    echo "# Job Details"
-    echo
-    echo "* Job ID: $jobid"
-    echo
-
     ## An active job?
     bfr=$(qstat -j "$jobid" 2> /dev/null)
-    res=$?
-    if [[ $res -eq 0 ]]; then
-	echo "$bfr"
+    if [[ $? == 0 ]]; then
+        ## Keep key: value lines
+        vars=$(grep -E "^[^:]+:.*" <<< "$bfr")
+        ## Fix keys
+        vars=$(sed ':loop; s/^\([^:]*\) \+\([^:]*:\)/\1_\2/; t loop' <<< "$vars" | sed -E 's/__+/_/g')
+        ## Turn into _THIS_JOB_keys="value"
+        vars=$(sed -E 's/^([^:]+):[[:space:]]*(.*)/_THIS_JOB_\1="\2"/' <<< "$vars")
+	echo "------------------------"
+        ## Parse as environment variables
+        while IFS= read -r line; do
+            eval "export $line"
+        done <<< "$vars"
+        env | grep -F "_THIS_JOB_" | sort
+
+        ## Get additional info on the job
+        bfr2=$(qstat -u "${_THIS_JOB_owner}" | grep -E "^[[:space:]]*\b${_THIS_JOB_job_number}\b[[:space:]]")
+
+        ## Summarize
+        ruler "-"
+        echo "Job Details"
+        ruler "-"
+        echo
+
+        value=${_THIS_JOB_job_number}
+        echo "[ $ok ] Job ID: ${value}"
+
+        value=${_THIS_JOB_job_name}
+        echo "[ $ok ] Job name: ${value}"
+
+        ## Current status
+        mapfile -t values < <(awk '{ print $5 }' <<< "$bfr2")
+        level=0
+        values2=()
+        for kk in $(seq "${#values[@]}"); do
+            value=${values[$((kk - 1))]}
+
+            value=${value/d/00}
+            value=${value/E/01}
+            value=${value/h/02}
+            value=${value/q/03}
+            value=${value/r/04}
+            value=${value/R/05}
+            value=${value/s/0S}
+            value=${value/S/06}
+            value=${value/t/07}
+            value=${value/T/08}
+            value=${value/w/09}
+            value=${value/z/10}
+
+            value=${value/00/${yellow}deletion${reset} }
+            value=${value/01/${red}error${reset} }
+            value=${value/02/${yellow}hold${reset} }
+            value=${value/03/${yellow}queued${reset} }
+            value=${value/04/${green}running${reset} }
+            value=${value/05/${blue}restarted${reset} }
+            value=${value/06/${yellow}suspended${reset} }
+            value=${value/07/${blue}transfering${reset} }
+            value=${value/08/${yellow}threshold${reset} }
+            value=${value/09/${blue}waiting${reset} }
+            value=${value/10/${red}zombie${reset} }
+
+            if [[ $level -lt 2 ]]; then
+                if [[ $value == *error* ]]; then
+                    level=2
+                elif [[ $value == *zombie* ]]; then
+                    level=2
+                fi
+            fi
+
+            if [[ $level -lt 1 ]]; then
+                if [[ $value == *deletion* ]]; then
+                    level=1
+                elif [[ $value == *hold* ]]; then
+                    level=1
+                elif [[ $value == *queued* ]]; then
+                    level=1
+                elif [[ $value == *threshold* ]]; then
+                    level=1
+                fi
+            fi
+            values2+=("$value")
+        done
+        status="[ $ok ]"
+        if [[ $level == 1 ]]; then
+            status="[$warn]"
+        elif [[ $level == 2 ]]; then
+            status="[$fail]"
+        fi
+        echo "$status Job status: [n=${#values[@]}] ${values[*]} => ${values2[*]}"
+
+        value=${_THIS_JOB_owner}
+        is_owner=true
+        status="[ $ok ]"
+        info=""
+        if [[ $value != $USER ]]; then
+            is_owner=false
+            status="[$warn]"
+            info=" ${yellow}WARNING: You ($USER) are not the owner of this job${reset}"
+        fi
+        echo "$status Job owner: ${value}${info}"
+
+        value=${_THIS_JOB_submission_time}
+        status="[ $ok ]"
+        info=""
+        epoch=$(date -d "${value}" '+%s' 2> /dev/null)
+	if [[ $? != 0 ]]; then
+            timestamp="${value}"
+            status="[$warn]"
+            info=" ${yellow}WARNING: Failed to parse timestamp${reset}"
+        else
+            timestamp=$(date -d "@${epoch}" '+%A %Y-%m-%dT%H:%M:%S%z' 2> /dev/null)
+	    epoch_now=$(date "+%s")
+	    mins=$(( (epoch_now - epoch) / 60 ))
+	    hours=$(( (epoch_now - epoch) / 3600 ))
+	    days=$(( hours / 24 ))
+            hours2=$(( hours - 24 * days ))
+            mins2=$(( mins - 60 * hours ))
+            info="${days}d${hours2}h${mins2}m ago"
+            if [[ $hours -gt 24 ]]; then
+                info="${red}${info}${reset}"
+                status="[$warn]"
+            elif [[ $hours -gt 6 ]]; then
+                info="${yellow}${info}${reset}"
+                status="[$warn]"
+            fi
+            info=" [${info}]"
+        fi
+        echo "$status Submitted on: ${timestamp}${info}"
+
+        value=${_THIS_JOB_hard_queue_list}
+        status="[ $ok ]"
+        info=""
+        echo "$status Job queue: ${value}"
+
+        value=${_THIS_JOB_cwd}
+        status="[ $ok ]"
+        info=""
+        if ! ${is_owner}; then
+            status="[$warn]"
+        elif [[ ! -w "${value}" ]]; then
+            info=" ${red}ERROR: User '${_THIS_JOB_sge_o_log_name}' lacks write permission to folder${reset}"
+            status="[$warn]"
+        fi           
+        echo "${status} Working directory: $(dir_info "${value}" "${is_owner}")${info}"
+
+        value=${_THIS_JOB_sge_o_workdir}
+        status="[ $ok ]"
+        info=""
+        if ! ${is_owner}; then
+            status="[$warn]"
+        elif [[ ! -w "${value}" ]]; then
+            info=" ${red}ERROR: User '${_THIS_JOB_sge_o_log_name}' lacks write permission to folder${reset}"
+            status="[$fail]"
+        fi           
+        echo "${status} Log directory: $(dir_info "${value}" "${is_owner}")${info}"
+
+        ## Was there a launch error?
+        if [[ -n $_THIS_JOB_error_reason_1 ]]; then
+            echo "[$fail] ${red}ERROR: ${_THIS_JOB_error_reason_1}${reset}"
+            exit
+        fi
+
+#        job_id=$(grep -E "^job_number:" <<< "${bfr}" | sed 's/^[^ ]*[ ]*//')
+#        submit_time=$(grep -E "^submission_time:" <<< "${bfr}" | sed 's/^[^ ]*[ ]*//')
+#	echo "$bfr"
 	exit 0
     fi
 
