`wynton job` now detects `-l rocky8=false` as a FAIL

diff --git a/bin/wynton-job b/bin/wynton-job
--- a/bin/wynton-job
+++ b/bin/wynton-job
@@ -400,7 +400,21 @@ if [[ $action == "job" ]]; then
 
         # shellcheck disable=2154
         value=${_THIS_JOB_hard_resource_list}
+
+        is_rocky8=true
+	key="rocky8"
+        if grep -q -F "${key}" <<< "${value}"; then
+            value2=$(sed -E "s/.*\b${key}=(true|false)($|,.*)/\1/" <<< "${value}")
+	    if [[ ${value2} != "true" ]]; then
+		is_rocky8=false
+	    fi
+        fi
+	
         status="[ $ok ]"
+        if ! ${is_rocky8}; then
+            status="[$fail]"
+	fi
+
         info=""
         echo "$status Requested resources: ${value}"
 	
@@ -430,6 +444,10 @@ if [[ $action == "job" ]]; then
             value2=$(sed -E "s/.*\b${key}=(${pattern_size})($|,.*)/\1/" <<< "${value}")
 	    mapfile -t sizes < <(parse_size_spec "${value2}")
             echo "       - ${key}=${value2} => $(printf "%'.1f" "${sizes[SIZES_MiB]}") MiB = $(printf "%'.1f" "${sizes[SIZES_GiB]}") GiB"
+        fi
+
+        if ! ${is_rocky8}; then
+            echo "       - rocky8=${red}false${reset} <= ERROR: Not supported value"
         fi
 
         # shellcheck disable=2154
