wynton-sessioninfo: Add option --user=<name>

diff --git a/bin/wynton-sessioninfo b/bin/wynton-sessioninfo
--- a/bin/wynton-sessioninfo
+++ b/bin/wynton-sessioninfo
@@ -126,6 +126,20 @@ while [[ $# -gt 0 ]]; do
         debug=true
     elif test "$1" == "--verbose"; then
         verbose=true
+    ## Options (--key=value):
+    elif [[ "$1" =~ ^--.*=.*$ ]]; then
+        key=${1//--}
+        key=${key//=*}
+        value=${1//--[[:alpha:]]*=}
+        if [[ -z ${value} ]]; then
+            error "Option '--${key}=<value>' must not be empty"
+        fi
+        if [[ "${key}" == "user" ]]; then
+            user="${value}"
+        else
+            echo >&2 "ERROR: Unknown option: $1"
+            exit 2
+        fi
     else
         extras="$extras $1"
     fi
