Validate SGE

diff --git a/bin/wynton-account b/bin/wynton-account
--- a/bin/wynton-account
+++ b/bin/wynton-account
@@ -68,13 +68,13 @@ while [[ $# -gt 0 ]]; do
         debug=true
     elif test "$1" == "--verbose"; then
         verbose=true
-	
+
     ## Deprecated
     elif test "$1" == "--user"; then
-	shift
+        shift
         user=$1
-	mdeprecated "Command-line option format '$1 <value>' is deprecated. Please use '$1=<value>' instead"
-	
+        mdeprecated "Command-line option format '$1 <value>' is deprecated. Please use '$1=<value>' instead"
+        
     ## Options (--key=value):
     elif [[ "$1" =~ ^--.*=.*$ ]]; then
         key=${1//--}
@@ -136,46 +136,46 @@ if [[ $action == "validate" ]]; then
     same_user=true
     if [[ "${user}" != "${USER}" ]]; then
         same_user=false
-	warn "Running as user '${USER}' != '${user}'"
-	echo >&2
+        warn "Running as user '${USER}' != '${user}'"
+        echo >&2
     fi
     
     mapfile -t ldap_info < <(ldap_search "uid=${user}" "+" "*" | sort)
-    printf "%s\n" "${ldap_info[@]}"
-
+    #    printf "%s\n" "${ldap_info[@]}"
+    
     # No duplicated username
     count=$(ldap_get_field "uid" "${ldap_info[@]}" | wc -l)
     if [[ ${count} -gt 1 ]]; then
-	error "There are ${count} users in LDAP with username '${user}'"
+        error "There are ${count} users in LDAP with username '${user}'"
     fi
 
     phi=false
     if [[  $(ldap_get_field "protectedAccess" "${ldap_info[@]}") == "TRUE" ]]; then
-	phi=true
+        phi=true
     fi
 
     if ${same_user}; then
-	running_as_phi=${phi}
+        running_as_phi=${phi}
     else
-	if [[ "$(ldap_search "uid=${USER}" "protectedAccess" | ldap_get_field "protectedAccess")" == "TRUE" ]]; then
+        if [[ "$(ldap_search "uid=${USER}" "protectedAccess" | ldap_get_field "protectedAccess")" == "TRUE" ]]; then
             running_as_phi=true
-	else
+        else
             running_as_phi=false
-	fi
+        fi
     fi
-    if [[ ${running_as_phi} != ${phi} ]]; then
+    if [[ ${running_as_phi} != "${phi}" ]]; then
         warn "Cannot run all checks on PHI user, because running as a non-PHI user"
-	echo >&2
+        echo >&2
     fi
     
     access=false
     if [[  $(ldap_get_field "wyntonAccess" "${ldap_info[@]}") == "TRUE" ]]; then
-	access=true
+        access=true
     fi
 
     locked=false
     if [[  $(ldap_get_field "isLocked" "${ldap_info[@]}") == "TRUE" ]]; then
-	locked=true
+        locked=true
     fi
     
     email=$(ldap_get_field "mail" "${ldap_info[@]}")
@@ -183,6 +183,7 @@ if [[ $action == "validate" ]]; then
     shell=$(ldap_get_field "loginShell" "${ldap_info[@]}")
     faculty_sponsor=$(ldap_get_field "FacultySponsor" "${ldap_info[@]}")
 
+    
     echo "# Account Validation"
     echo
     echo "## Overview"
@@ -211,87 +212,87 @@ if [[ $action == "validate" ]]; then
     # No 'reserved' usernames
     mapfile -t reserved < <(reserved_usernames)
     if [[ " ${reserved[@]} " =~ " ${user} " ]]; then
-	echo "[FAIL] Username is a 'reserved' username and should not be used"
-	n_fail=$((n_fail + 1))
+        echo "[FAIL] Username is a 'reserved' username and should not be used"
+        n_fail=$((n_fail + 1))
     else
-	echo "[ OK ] Username is not a 'reserved' username"
-	n_ok=$((n_ok + 1))
+        echo "[ OK ] Username is not a 'reserved' username"
+        n_ok=$((n_ok + 1))
     fi
 
     # No duplicated UID
     mapfile -t res < <(ldap_search "uidNumber=${uid}" "uid" | ldap_get_field "uid")
     if [[ ${#res[@]} -gt 1 ]]; then
-	echo "[FAIL] User ID (UID) is not unique: [n=${res[@]}] ${res[*]}"
-	n_fail=$((n_fail + 1))
+        echo "[FAIL] User ID (UID) is not unique: [n=${#res[@]}] ${res[*]}"
+        n_fail=$((n_fail + 1))
     else
-	echo "[ OK ] User ID (UID) is unique"
-	n_ok=$((n_ok + 1))
+        echo "[ OK ] User ID (UID) is unique"
+        n_ok=$((n_ok + 1))
     fi
 
     # UIDs within [1023,65535]
     if [[ ${uid} -lt 1023 ]] || [[ ${uid} -gt 65535 ]]; then
-	echo "[FAIL] User ID (UID) is out of range [1023,65535]"
-	n_fail=$((n_fail + 1))
+        echo "[FAIL] User ID (UID) is out of range [1023,65535]"
+        n_fail=$((n_fail + 1))
     else
-	echo "[ OK ] User ID (UID) is within [1023,65535]"
-	n_ok=$((n_ok + 1))
+        echo "[ OK ] User ID (UID) is within [1023,65535]"
+        n_ok=$((n_ok + 1))
     fi
 
     # GIDs within [455,65535]
     if [[ ${gid} -lt 455 ]] || [[ ${gid} -gt 65535 ]]; then
-	echo "[FAIL] Group ID (GID) is out of range [455,65535]"
-	n_fail=$((n_fail + 1))
+        echo "[FAIL] Group ID (GID) is out of range [455,65535]"
+        n_fail=$((n_fail + 1))
     else
-	echo "[ OK ] Group ID (GID) is within [415,65535]"
-	n_ok=$((n_ok + 1))
+        echo "[ OK ] Group ID (GID) is within [415,65535]"
+        n_ok=$((n_ok + 1))
     fi
 
     # PHI user is in 'wynton-phi', otherwise not
     if ${phi}; then
         if id "${user}" | grep -q -F "(wynton-phi)"; then
-	    echo "[ OK ] PHI user is in 'wynton-phi' group"
-	    n_ok=$((n_ok + 1))
+            echo "[ OK ] PHI user is in 'wynton-phi' group"
+            n_ok=$((n_ok + 1))
         else
-	    echo "[FAIL] PHI user is not in 'wynton-phi' group"
-	    n_fail=$((n_fail + 1))
-	fi
+            echo "[FAIL] PHI user is not in 'wynton-phi' group"
+            n_fail=$((n_fail + 1))
+        fi
     else
         if id "${user}" | grep -q -F "(wynton-phi)"; then
-	    echo "[FAIL] Non-PHI user is in 'wynton-phi' group"
-	    n_fail=$((n_fail + 1))
+            echo "[FAIL] Non-PHI user is in 'wynton-phi' group"
+            n_fail=$((n_fail + 1))
         else
-	    echo "[ OK ] Non-PHI user is not in 'wynton-phi' group"
-	    n_ok=$((n_ok + 1))
-	fi
+            echo "[ OK ] Non-PHI user is not in 'wynton-phi' group"
+            n_ok=$((n_ok + 1))
+        fi
     fi
     
     # No duplicated home directories
     mapfile -t res < <(ldap_search "homeDirectory=${home}" "homeDirectory" | ldap_get_field "homeDirectory")
     if [[ ${#res[@]} -gt 1 ]]; then
-	echo "[FAIL] HOME folder is not unique: [n=${res[@]}] ${res[*]}"
-	n_fail=$((n_fail + 1))
+        echo "[FAIL] HOME folder is not unique: [n=${#res[@]}] ${res[*]}"
+        n_fail=$((n_fail + 1))
     else
-	echo "[ OK ] HOME folder is unique"
-	n_ok=$((n_ok + 1))
+        echo "[ OK ] HOME folder is unique"
+        n_ok=$((n_ok + 1))
     fi
     
     # Users has a HOME directories under expected /wynton/ location
     if ${phi}; then
-	expected="/wynton/protected/home/{group}/"
+        expected="/wynton/protected/home/{group}/"
     else
-	expected="/wynton/home/{group}/"
+        expected="/wynton/home/{group}/"
     fi
     pattern=$(sed 's/{group}/[[:alnum:]_.-]+/' <<< "${expected}")
     if grep -q -E "^${pattern}" <<< "${home}"; then
-	echo "[ OK ] HOME folder is under ${expected}"
-	n_ok=$((n_ok + 1))
+        echo "[ OK ] HOME folder is under ${expected}"
+        n_ok=$((n_ok + 1))
     else
-	echo "[FAIL] HOME folder is not under ${expected}"
-	n_fail=$((n_fail + 1))
+        echo "[FAIL] HOME folder is not under ${expected}"
+        n_fail=$((n_fail + 1))
     fi
 
     if [[ ${EUID} -ne 0 ]] && ${phi} && ! ${running_as_phi}; then
-	skip=true
+        skip=true
     else
         skip=false
     fi
@@ -320,60 +321,60 @@ if [[ $action == "validate" ]]; then
     # No duplicated email addresses
     mapfile -t res < <(ldap_search "mail=${email}" "mail" | ldap_get_field "mail")
     if [[ ${#res[@]} -gt 1 ]]; then
-	echo "[FAIL] Email address is not unique: [n=${res[@]}] ${res[*]}"
-	n_fail=$((n_fail + 1))
+        echo "[FAIL] Email address is not unique: [n=${#res[@]}] ${res[*]}"
+        n_fail=$((n_fail + 1))
     else
-	echo "[ OK ] Email address is unique"
-	n_ok=$((n_ok + 1))
+        echo "[ OK ] Email address is unique"
+        n_ok=$((n_ok + 1))
     fi
     
     # Valid email address
     if grep -q -i -E "$(email_pattern)" <<< "${email}"; then
-	echo "[ OK ] Email address has a valid format"
-	n_ok=$((n_ok + 1))
+        echo "[ OK ] Email address has a valid format"
+        n_ok=$((n_ok + 1))
     else
-	echo "[FAIL] Email address does not have a valid format"
-	n_fail=$((n_fail + 1))
+        echo "[FAIL] Email address does not have a valid format"
+        n_fail=$((n_fail + 1))
     fi
 
     # Valid UCSF ID
     if [[ -n "${ucsf_id}" ]]; then
         if valid_ucsf_id "${ucsf_id}"; then
-	    echo "[ OK ] UCSF Employee ID is valid"
+            echo "[ OK ] UCSF Employee ID is valid"
             n_ok=$((n_ok + 1))
         else
-	    echo "[FAIL] UCSF Employee ID is invalid"
-	    n_fail=$((n_fail + 1))
-	fi
+            echo "[FAIL] UCSF Employee ID is invalid"
+            n_fail=$((n_fail + 1))
+        fi
 
         # No duplicated UCSF ID
         mapfile -t res < <(ldap_search "ucsfIDNumber=${ucsf_id}" "ucsfIDNumber" | ldap_get_field "ucsfIDNumber")
         if [[ ${#res[@]} -gt 1 ]]; then
-            echo "[FAIL] UCSF Employee ID is not unique: [n=${res[@]}] ${res[*]}"
-	    n_fail=$((n_fail + 1))
-        else
-	    echo "[ OK ] UCSF Employee ID is unique"
-	    n_ok=$((n_ok + 1))
-	fi
-    else
-	if is_ucsf_email "${email}"; then
-	    echo "[FAIL] UCSF Employee ID is missing"
+            echo "[FAIL] UCSF Employee ID is not unique: [n=${#res[@]}] ${res[*]}"
             n_fail=$((n_fail + 1))
-	else
-	    echo "[ OK ] UCSF Employee ID is not required"
-	    n_skip=$((n_skip + 1))
-	fi
+        else
+            echo "[ OK ] UCSF Employee ID is unique"
+            n_ok=$((n_ok + 1))
+        fi
+    else
+        if is_ucsf_email "${email}"; then
+            echo "[FAIL] UCSF Employee ID is missing"
+            n_fail=$((n_fail + 1))
+        else
+            echo "[ OK ] UCSF Employee ID is not required"
+            n_skip=$((n_skip + 1))
+        fi
     fi
 
     # No locked account has access
     if ${locked}; then
         if ${access}; then
-	    echo "[FAIL] Locked account still have access"
-	    n_fail=$((n_fail + 1))
-	else
-	    echo "[ OK ] Locked account does not have access"
-	    n_fail=$((n_fail + 1))
-	fi
+            echo "[FAIL] Locked account still have access"
+            n_fail=$((n_fail + 1))
+        else
+            echo "[ OK ] Locked account does not have access"
+            n_fail=$((n_fail + 1))
+        fi
     else
          echo "[ OK ] Account is not locked"
          n_skip=$((n_skip + 1))
@@ -381,72 +382,90 @@ if [[ $action == "validate" ]]; then
 
     # Login shell is valid
     if [[ -z ${shell} ]]; then
-	echo "[FAIL] Login shell is not specified"
-	n_fail=$((n_fail + 1))
+        echo "[FAIL] Login shell is not specified"
+        n_fail=$((n_fail + 1))
     else
         if [[ ! -f "${shell}" ]]; then
-	    echo "[FAIL] Login shell does not exist"
-	    n_fail=$((n_fail + 1))
+            echo "[FAIL] Login shell does not exist"
+            n_fail=$((n_fail + 1))
         elif [[ ! -x "${shell}" ]]; then
-	    echo "[FAIL] Login shell is non-executable"
-	    n_fail=$((n_fail + 1))
-	else
-	    echo "[ OK ] Login shell is an executable"
-	fi
+            echo "[FAIL] Login shell is non-executable"
+            n_fail=$((n_fail + 1))
+        else
+            echo "[ OK ] Login shell is an executable"
+        fi
     fi
 
     # Faculty sponsor is valid
     if [[ -z ${faculty_sponsor} ]]; then
-	echo "[FAIL] Faculty sponsor is missing"
-	n_fail=$((n_fail + 1))
+        echo "[FAIL] Faculty sponsor is missing"
+        n_fail=$((n_fail + 1))
     else
-	pattern="^([[:alpha:] .'-]+)[[:blank:]]+<([^>]+)>$"
+        pattern="^([[:alpha:] .'-]+)[[:blank:]]+<([^>]+)>$"
         if grep -q -i -E "${pattern}" <<< "${faculty_sponsor}"; then
-	    faculty_sponsor_fullname=$(sed -E "s/${pattern}/\1/" <<< "${faculty_sponsor}")
-	    faculty_sponsor_email=$(sed -E "s/${pattern}/\2/" <<< "${faculty_sponsor}")
+            faculty_sponsor_fullname=$(sed -E "s/${pattern}/\1/" <<< "${faculty_sponsor}")
+            faculty_sponsor_email=$(sed -E "s/${pattern}/\2/" <<< "${faculty_sponsor}")
             if [[ -z "${faculty_sponsor_fullname}" ]]; then
-	        echo "[FAIL Faculty sponsor lacks a full name"
-	        n_fail=$((n_fail + 1))
+                echo "[FAIL Faculty sponsor lacks a full name"
+                n_fail=$((n_fail + 1))
             elif [[ -z "${faculty_sponsor_email}" ]]; then
-	        echo "[FAIL Faculty sponsor lacks an email address"
-	        n_fail=$((n_fail + 1))
+                echo "[FAIL Faculty sponsor lacks an email address"
+                n_fail=$((n_fail + 1))
             elif ! grep -q -i -E "$(email_pattern)" <<< "${faculty_sponsor_email}"; then
-	        echo "[FAIL Faculty sponsor email address is not a valid address"
-	    else
-	        echo "[ OK ] Faculty sponsor has a full name and email address"
+                echo "[FAIL Faculty sponsor email address is not a valid address"
+            else
+                echo "[ OK ] Faculty sponsor has a full name and email address"
                 n_ok=$((n_ok + 1))
-	    fi
+            fi
         else
-	    echo "[FAIL] Faculty sponsor does not have a full name and email address"
-	    n_fail=$((n_fail + 1))
-	fi
+            echo "[FAIL] Faculty sponsor does not have a full name and email address"
+            n_fail=$((n_fail + 1))
+        fi
     fi
     
     # No mixed 'wyntonAccess'
     mapfile -t res < <(printf "%s\n" "${ldap_info[@]}" | grep -E "^wyntonAccess:")
     if [[ ${#res[@]} -gt 1 ]]; then
-	echo "[FAIL] User has multiple LDAP 'wyntonAccess' entries: [n=${#res[@]}] ${res[*]}"
-	n_fail=$((n_fail + 1))
+        echo "[FAIL] User has multiple LDAP 'wyntonAccess' entries: [n=${#res[@]}] ${res[*]}"
+        n_fail=$((n_fail + 1))
     else
-	echo "[ OK ] User has unique LDAP 'wyntonAccess' entry"
-	n_ok=$((n_ok + 1))
+        echo "[ OK ] User has unique LDAP 'wyntonAccess' entry"
+        n_ok=$((n_ok + 1))
     fi
 
     # No mixed 'protectedAccess'
     mapfile -t res < <(printf "%s\n" "${ldap_info[@]}" | grep -E "^protectedAccess:")
     if [[ ${#res[@]} -gt 1 ]]; then
-	echo "[FAIL] User has multiple LDAP 'protectedAccess' entries: [n=${#res[@]}] ${res[*]}"
-	n_fail=$((n_fail + 1))
+        echo "[FAIL] User has multiple LDAP 'protectedAccess' entries: [n=${#res[@]}] ${res[*]}"
+        n_fail=$((n_fail + 1))
     else
-	echo "[ OK ] User has unique LDAP 'protectedAccess' entry"
-	n_ok=$((n_ok + 1))
+        echo "[ OK ] User has unique LDAP 'protectedAccess' entry"
+        n_ok=$((n_ok + 1))
     fi
 
+    if qconf -suserl | grep -q -E "^${user}$"; then
+        mapfile -t sge_info < <(qconf -suser "${user}")        
+        echo "[ OK ] User is in SGE"
+        n_ok=$((n_ok + 1))
+        wynton_project=$(ldap_get_field "wyntonProject" "${ldap_info[@]}")
+        sge_project=$(sge_get_field "default_project" "${sge_info[@]}")
+        if [[ ${wynton_project} == "${sge_project}" ]]; then
+            echo "[ OK ] SGE 'default_project' and LDAP 'wyntonProject' agree"
+            n_ok=$((n_ok + 1))
+        else
+            echo "[FAIL] SGE 'default_project' and LDAP 'wyntonProject' do not agree"
+            n_fail=$((n_fail + 1))
+        fi
+    else
+        echo "[FAIL] User is not in SGE"
+        n_fail=$((n_fail + 1))
+    fi
+    
     echo
     echo "Summary: ${n_ok} OK, ${n_fail} FAIL, ${n_skip} SKIP"
 
     if [[ ${n_fail} -gt 0 ]]; then
-	echo >&2
+        echo >&2
         error "Detected ${n_fail} FAIL:s"
     fi
 fi
