wynton-sessioninfo: Warn about non-private folders and files. Warn about CRLF. Warn about missing folders in path env vars

diff --git a/bin/wynton-sessioninfo b/bin/wynton-sessioninfo
--- a/bin/wynton-sessioninfo
+++ b/bin/wynton-sessioninfo
@@ -39,11 +39,75 @@ source "${incl}/system.sh"
 # -------------------------------------------------------------------------
 # SPECIFIC
 # -------------------------------------------------------------------------
+warn_crlf() {
+    local file=${1:?}
+    
+    if [[ -f "${file}" ]]; then
+	if grep -q "CRLF" <<< "$(file ${file})"; then
+            warn "File uses CRLF line endings. Run 'dos2unix ${file}' to fix this"
+	fi
+    fi
+}
+
+warn_non_private() {
+    local file=${1:?}
+    local what
+    
+    if [[ -e "${file}" ]]; then
+	if grep -v -q "^.00$" <<< $(stat -c "%a" "${file}"); then
+	    what="File"
+	    if [[ -d "${file}" ]]; then
+                what="Directory"
+	    fi
+            warn "${what} '${file}' can be accessed by other users. Fix by calling 'chmod go-rwx \"${file}\"'"
+	fi
+    fi
+}
+
+#' Assert that all folders specified in a "path" environment variable exist
+#'
+#' Usage: assert_envpath <envvar> [exclude]*
+#'
+#' Examples:
+#' assert_envpath LD_LIBRARY_PATH
+#'
+#' # Same, but ignore anything under HOME
+#' assert_envpath LD_LIBRARY_PATH "$HOME"
+warn_envpath_missing() {
+    local name=${1:?}
+    local path=${!name}    
+    local excl
+    local -a missing
+
+    ## Nothing to do?
+    [[ -z ${path} ]] && return 0
+
+    shift
+    excl=$(IFS="|"; echo "$*")
+    
+    IFS=':' read -r -a dirs <<< "$path"
+    for dir in "${dirs[@]}"; do
+    [[ -z ${dir} ]] && continue
+    [[ -n ${excl} ]] && grep -q -E "${excl}" <<< "$dir" && continue
+        [[ -d "${dir}" ]] || { missing+=( "$dir" ); continue; }
+        [[ -r "${dir}" ]] || { missing+=( "$dir [no permission]" ); continue; }
+        [[ -x "${dir}" ]] || { missing+=( "$dir [no recursive permission]" ); continue; }                                                                    
+    done
+    
+    if [[ ${#missing[@]} -gt 0 ]]; then
+        warn "Detected non-existing or inaccessible folder(s) in ${name}: [n=${#missing[@]}] ${missing[*]}"                                     
+        return 1
+    fi
+    
+    return 0
+}
 
 
 # -------------------------------------------------------------------------
 # MAIN
 # -------------------------------------------------------------------------
+term_colors enable
+
 ## Actions
 action=check
 
@@ -113,20 +177,25 @@ if [[ $action == "check" ]]; then
     echo "* SHELL=${SHELL:-<not set>}"
     for file in "$home/.bashrc" "$home/.bash_profile" "$home/.bash_logout"; do
         echo "* $(file_info "$file")"
+        warn_crlf "${file}"
     done
     echo
     
     echo "## SSH"
     dir=$home/.ssh
     echo "* $(dir_info "$dir")"
+    warn_non_private "${dir}"
     for file in "$home/.ssh/authorized_keys" "$home/known_hosts"; do
 	echo "* $(file_info "$file")"
+        warn_crlf "${file}"
     done	 
     echo
     
     echo "## Netrc"
     file=$home/.netrc
     echo "* $(file_info "$file")"
+    warn_crlf "${file}"
+    warn_non_private "${dir}"
     echo
     
     echo "## Conda"
@@ -140,15 +209,16 @@ if [[ $action == "check" ]]; then
     echo
     
     echo "## R"
-    file=$home/.Rprofile
-    echo "* $(file_info "$file")"
-    file=$home/.Renviron
-    echo "* $(file_info "$file")"
+    for file in "$home/.Rprofile" "$home/.Renviron"; do
+        echo "* $(file_info "$file")"
+        warn_crlf "${file}"
+    done
     echo
     
     if command -v module &> /dev/null; then
         echo "## Module environments"
         echo "* MODULEPATH=${MODULEPATH:-<not set>}"
+        warn_envpath_missing "MODULEPATH"
         module list 2> /dev/null || { echo "Currently Loaded Modules: <none>"; }
 	echo
     fi
@@ -161,7 +231,15 @@ if [[ $action == "check" ]]; then
     echo "* HOSTNAME=${HOSTNAME:-<not set>}"
     echo "* LANG=${LANG:-<not set>}"
     echo "* PATH=${PATH:-<not set>}"
+    warn_envpath_missing "PATH"
     echo "* LD_LIBRARY_PATH=${LD_LIBRARY_PATH:-<not set>}"
+    warn_envpath_missing "LD_LIBRARY_PATH"
+    echo "* INFOPATH=${INFOPATH:-<not set>}"
+    warn_envpath_missing "INFOPATH"
+    echo "* MANPATH=${MANPATH:-<not set>}"
+    warn_envpath_missing "MANPATH"
+    echo "* PKG_CONFIG_PATH=${PKG_CONFIG_PATH:-<not set>}"
+    warn_envpath_missing "PKG_CONFIG_PATH"
     echo
 fi
 
